server:
  port: 9100
  servlet:
    context-path: /

spring:
  application:
    name: mybaits_plus-springboot
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/excavate_database?characterEncoding=utf8
    username: root
    password: 12345


